"""empty message

Revision ID: 29150fba603c
Revises: a55893cf58d6
Create Date: 2020-04-25 17:31:35.959884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29150fba603c'
down_revision = 'a55893cf58d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('quantity', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('is_avaiable', sa.Boolean(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=True),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    # ### end Alembic commands ###
